<section class="banner-lista" id="home">
    <div class="cabecalho-home-lista">
    <header> <!--inicio header-->
                    <nav class="navbar navbar-expand-md navbar-light navbar-transparente"> <!--inicio nav-->
                        <div class="container"> <!--inicio container-->
                            <a href="/logado"><img class="logo" src="img/logo/logoPngSf.png"></a>


                            <button class="navbar-toggler" data-toggle="collapse" data-target="#nav-principal">  <!--inicio button-->
                            <i class="fas fa-bars text-white"></i>
                            </button> <!--final button-->

                            <div class="collapse navbar-collapse" id="nav-principal"> <!-- inicio div collapse-->

                            <ul class="navbar-nav ml-auto"> <!--inicio ul-->                            
                                <li class="nav-item">
                                <a href="/minhaConta" class="nav-link"><?= $this->view->nome?></a>
                                </li>
                                <li class="nav-item">
                                <a href="/escolherLista" class="nav-link">Minha lista</a>
                                </li>
                                <li class="nav-item">
                                <a href="/procurarListaLogado" class="nav-link">Procurar Lista</a>
                                </li>
                                <li class="nav-item">
                                <a href="/sair" class="nav-link">Sair</a>
                                </li>
                            </ul> <!--final ul-->

                            </div> <!--final div collapse-->

                        </div> <!--final container-->

                    </nav> <!--final nav-->

            </header> <!--final header-->
                
        <section class="container listaProdutos">

                <?php if($this->view->produtos){ ?>
                <?php foreach($this->view->produtos as $indice_arr => $produtos){ ?>
                    <div class="produtos">
                        <img src="<?= $produtos['imagem_produto']?>" class="img"></img>
                        <a href="<?= $produtos['link_produto'] ?>"><h2><?= $produtos['nome_produto']?></h2></a>
                        <h4 class="titMinhaLista">R$: <?= $produtos['valor_produto'] ?></h4>
                        <form action="/adicionarNaLista?id=<?= $produtos['id_produto'] ?>" method="POST">
                            <input type="hidden" name="idProduto" value="<?= $produtos['id_produto']; ?>">
                            <input type="hidden" name="nomeProduto" value="<?= $produtos['nome_produto']?>">
                            <input type="hidden" name="valorProduto" value="<?= $produtos['valor_produto'] ?>">
                            <input type="hidden" name="linkProduto" value="<?= $produtos['link_produto'] ?>">
                            <input type="number" class="form-control" name="quantidadeProduto">
                            <button type="submit" class="btn btn-custom btn-sm">Adicionar a lista</button>
                        </form>
                    </div>
                <?php } ?>
            <?php }else{ ?>
                <div class="infoSemLista">
                    <h2 class="semLista" >Nenhum produto associado</h2>
                </div>

            <?php } ?>

        </section>
    </div>  
    
    <footer>            
        <div class="container">
            <a href="/" class="titulo">Presentei.com</a> 
        </div>
    </footer>
</section>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

<!-- JavaScript (Opcional) -->
<!-- jQuery primeiro, depois Popper.js, depois Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
 


   
